apiVersion: apps/v1
kind: Deployment
metadata:
  name: lensassignment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lensassignment
  template:
    metadata:
      labels:
        app: lensassignment
    spec:
      containers:
      - name: lensassignment
        image: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/lensassignment:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
          - name: ENV_VARIABLE
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: ENV_VARIABLE
