apiVersion: networking.k8s.io/v1                          
kind: Ingress                                             # Type of Kubernetes resource
metadata:
  name: grafana-ingress                                   # Name of the Ingress resource
  namespace: monitoring                                   # Namespace where the Ingress resource will be created
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:                                                  # Defines the routing rule
  - host: grafana.LensAssignment.com                      # Specifies the hostname for accessing the service
    http:
      paths:
      - path: /                                           # URL path to match
        pathType: Prefix
        backend:
          service:
            name: grafana                                 # Specifies the Service name to route traffic to
            port:
              number: 80                                  # Specifies the port on the Service to which traffic will be forwarded
