# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: lensassignment-service
spec:
  selector:
    app: lensassignment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
